### ISSUE TITLE
Passing command line arguments and choosing the mode

### ISSUE THREAD

**Issue by gabhijit** [hyphenOs/webshark-backend#3]
Right now we have a number of things hard coded, plus we comment out some code to either run the server in the live capture mode or streaming Pcap files mode. This is fine for now, but we need to have a better control over it. Let's first start with two simple options `--live interface-name` and `--file path-to-filename.json`.

If None is selected, simply exit displaying the right feedback to the user. 

Once one of the option is selected, the `server` should run in that mode. This should avoid manual 'commenting' out of the unwanted code we do. 

We should use `yargs` to parse the arguments - if none is specified, force user to choose a mode. 

Once this basic support is in place, we can then extend it later for supporting more features. like 
* giving redis queue to check
* specifying interface to stream 
* support batching and batchsize (in both `file` and `live` mode). 

We'll add support for those features later.

**Comment by AniruddhaTayade123** [comment]
@gabhijit 
Need some clarification on this issue.
Arguments parsing part using yargs was understood. 
Choosing mode is what I am a little confused about. If the user runs without specifying any environment variable, then prompt user to choose either prod or dev mode. Is that right?

**Comment by gabhijit** [comment]
@AniruddhaTayade123 : Okay May be the description is not correct - 

Right now it's possible to simply run the server using `yarn start`. Now the problem with that mode is - We do not know whether the user wishes to run 'server' for live packet capture or using the pcap file. So one of the two arguments is a 'required' argument'. So if the user does not 'pass' the argument, the `yarn start` should exit with an error-code and give following message. 

```bash
Usage: yarn start --live <interface-name> | --file <path-to-pcap-filename>
```
So that user can now start with `yarn start --live  eth0` say.

Getting this working is a bit involved on windows (though not entirely impossible!)

**Comment by AniruddhaTayade123** [comment]
@gabhijit 
Understood. Thank you for providing the details.

**Comment by AniruddhaTayade123** [comment]
@gabhijit 
Implementation approach:

1. Importing 'yargs' into server.js file.
2. Adding code to parse arguments using 'yargs'.
3. Checking whether the argument is passed or not. If yes, then checking whether the argument is via  '--live flag' or '--file flag' and if argument is not specified then exit with a text display.

Does it seem fine?

**Comment by gabhijit** [comment]
Yes. That seems about right! I don't think a separate check of whether - argument passed or not is required - you have to check for one of the two flags to be present or bail out.

**Comment by gabhijit** [comment]
@AniruddhaTayade123 : Perhaps the issue is not clear enough in terms of what functionality is expected. I have updated the issue now. Hope it is clear.

**Comment by gabhijit** [comment]
The basic support for `yargs` and `--live` and `--file` is in place. Closing this issue.

**Comment by AniruddhaTayade123** [comment]
Hello sir, I checked the code. I realised that I was on a different track
but after going through the modified code by you, I have now understood it
properly.
Thank you very much!
